#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanAoDoAn.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATA-SHOP-QUAN-AO")]
	public partial class DbWebQuanAoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAU(MAU instance);
    partial void UpdateMAU(MAU instance);
    partial void DeleteMAU(MAU instance);
    partial void InsertLOAI_SP(LOAI_SP instance);
    partial void UpdateLOAI_SP(LOAI_SP instance);
    partial void DeleteLOAI_SP(LOAI_SP instance);
    partial void InsertSAN_PHAM(SAN_PHAM instance);
    partial void UpdateSAN_PHAM(SAN_PHAM instance);
    partial void DeleteSAN_PHAM(SAN_PHAM instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertKICH_THUOC(KICH_THUOC instance);
    partial void UpdateKICH_THUOC(KICH_THUOC instance);
    partial void DeleteKICH_THUOC(KICH_THUOC instance);
    partial void InsertHINH_ANH(HINH_ANH instance);
    partial void UpdateHINH_ANH(HINH_ANH instance);
    partial void DeleteHINH_ANH(HINH_ANH instance);
    #endregion
		
		public DbWebQuanAoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATA_SHOP_QUAN_AOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAU> MAUs
		{
			get
			{
				return this.GetTable<MAU>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_SP> LOAI_SPs
		{
			get
			{
				return this.GetTable<LOAI_SP>();
			}
		}
		
		public System.Data.Linq.Table<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this.GetTable<SAN_PHAM>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<KICH_THUOC> KICH_THUOCs
		{
			get
			{
				return this.GetTable<KICH_THUOC>();
			}
		}
		
		public System.Data.Linq.Table<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this.GetTable<HINH_ANH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAU")]
	public partial class MAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_MAU;
		
		private string _TEN_MAU;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_MAUChanging(string value);
    partial void OnMA_MAUChanged();
    partial void OnTEN_MAUChanging(string value);
    partial void OnTEN_MAUChanged();
    #endregion
		
		public MAU()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MAU", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_MAU
		{
			get
			{
				return this._MA_MAU;
			}
			set
			{
				if ((this._MA_MAU != value))
				{
					this.OnMA_MAUChanging(value);
					this.SendPropertyChanging();
					this._MA_MAU = value;
					this.SendPropertyChanged("MA_MAU");
					this.OnMA_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MAU", DbType="NVarChar(20)")]
		public string TEN_MAU
		{
			get
			{
				return this._TEN_MAU;
			}
			set
			{
				if ((this._TEN_MAU != value))
				{
					this.OnTEN_MAUChanging(value);
					this.SendPropertyChanging();
					this._TEN_MAU = value;
					this.SendPropertyChanged("TEN_MAU");
					this.OnTEN_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="MA_MAU", OtherKey="MA_MAU")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.MAU = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.MAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_SP")]
	public partial class LOAI_SP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_LOAI;
		
		private string _TEN_LOAI;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LOAIChanging(int value);
    partial void OnMA_LOAIChanged();
    partial void OnTEN_LOAIChanging(string value);
    partial void OnTEN_LOAIChanged();
    #endregion
		
		public LOAI_SP()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI", DbType="NVarChar(20)")]
		public string TEN_LOAI
		{
			get
			{
				return this._TEN_LOAI;
			}
			set
			{
				if ((this._TEN_LOAI != value))
				{
					this.OnTEN_LOAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI = value;
					this.SendPropertyChanged("TEN_LOAI");
					this.OnTEN_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SP_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="MA_LOAI", OtherKey="MA_LOAI")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SP = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAN_PHAM")]
	public partial class SAN_PHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SP;
		
		private string _MA_MAU;
		
		private System.Nullable<int> _MA_LOAI;
		
		private string _TEN_SP;
		
		private System.Nullable<double> _GIA_MUA;
		
		private System.Nullable<double> _GIA_BAN;
		
		private System.Nullable<int> _SL;
		
		private string _MO_TA;
		
		private string _HINH_ANH;
		
		private string _HINH_ANH1;
		
		private EntitySet<KICH_THUOC> _KICH_THUOCs;
		
		private EntitySet<HINH_ANH> _HINH_ANHs;
		
		private EntityRef<LOAI_SP> _LOAI_SP;
		
		private EntityRef<MAU> _MAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnMA_MAUChanging(string value);
    partial void OnMA_MAUChanged();
    partial void OnMA_LOAIChanging(System.Nullable<int> value);
    partial void OnMA_LOAIChanged();
    partial void OnTEN_SPChanging(string value);
    partial void OnTEN_SPChanged();
    partial void OnGIA_MUAChanging(System.Nullable<double> value);
    partial void OnGIA_MUAChanged();
    partial void OnGIA_BANChanging(System.Nullable<double> value);
    partial void OnGIA_BANChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnMO_TAChanging(string value);
    partial void OnMO_TAChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnHINH_ANH1Changing(string value);
    partial void OnHINH_ANH1Changed();
    #endregion
		
		public SAN_PHAM()
		{
			this._KICH_THUOCs = new EntitySet<KICH_THUOC>(new Action<KICH_THUOC>(this.attach_KICH_THUOCs), new Action<KICH_THUOC>(this.detach_KICH_THUOCs));
			this._HINH_ANHs = new EntitySet<HINH_ANH>(new Action<HINH_ANH>(this.attach_HINH_ANHs), new Action<HINH_ANH>(this.detach_HINH_ANHs));
			this._LOAI_SP = default(EntityRef<LOAI_SP>);
			this._MAU = default(EntityRef<MAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MAU", DbType="NVarChar(10)")]
		public string MA_MAU
		{
			get
			{
				return this._MA_MAU;
			}
			set
			{
				if ((this._MA_MAU != value))
				{
					if (this._MAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_MAUChanging(value);
					this.SendPropertyChanging();
					this._MA_MAU = value;
					this.SendPropertyChanged("MA_MAU");
					this.OnMA_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", DbType="Int")]
		public System.Nullable<int> MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					if (this._LOAI_SP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_SP", DbType="NVarChar(50)")]
		public string TEN_SP
		{
			get
			{
				return this._TEN_SP;
			}
			set
			{
				if ((this._TEN_SP != value))
				{
					this.OnTEN_SPChanging(value);
					this.SendPropertyChanging();
					this._TEN_SP = value;
					this.SendPropertyChanged("TEN_SP");
					this.OnTEN_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_MUA", DbType="Float")]
		public System.Nullable<double> GIA_MUA
		{
			get
			{
				return this._GIA_MUA;
			}
			set
			{
				if ((this._GIA_MUA != value))
				{
					this.OnGIA_MUAChanging(value);
					this.SendPropertyChanging();
					this._GIA_MUA = value;
					this.SendPropertyChanged("GIA_MUA");
					this.OnGIA_MUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_BAN", DbType="Float")]
		public System.Nullable<double> GIA_BAN
		{
			get
			{
				return this._GIA_BAN;
			}
			set
			{
				if ((this._GIA_BAN != value))
				{
					this.OnGIA_BANChanging(value);
					this.SendPropertyChanging();
					this._GIA_BAN = value;
					this.SendPropertyChanged("GIA_BAN");
					this.OnGIA_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_TA", DbType="NVarChar(MAX)")]
		public string MO_TA
		{
			get
			{
				return this._MO_TA;
			}
			set
			{
				if ((this._MO_TA != value))
				{
					this.OnMO_TAChanging(value);
					this.SendPropertyChanging();
					this._MO_TA = value;
					this.SendPropertyChanged("MO_TA");
					this.OnMO_TAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NVarChar(200)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH1", DbType="NVarChar(200)")]
		public string HINH_ANH1
		{
			get
			{
				return this._HINH_ANH1;
			}
			set
			{
				if ((this._HINH_ANH1 != value))
				{
					this.OnHINH_ANH1Changing(value);
					this.SendPropertyChanging();
					this._HINH_ANH1 = value;
					this.SendPropertyChanged("HINH_ANH1");
					this.OnHINH_ANH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_KICH_THUOC", Storage="_KICH_THUOCs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<KICH_THUOC> KICH_THUOCs
		{
			get
			{
				return this._KICH_THUOCs;
			}
			set
			{
				this._KICH_THUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_HINH_ANH", Storage="_HINH_ANHs", ThisKey="MA_SP", OtherKey="MA_HINH")]
		public EntitySet<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this._HINH_ANHs;
			}
			set
			{
				this._HINH_ANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SP_SAN_PHAM", Storage="_LOAI_SP", ThisKey="MA_LOAI", OtherKey="MA_LOAI", IsForeignKey=true)]
		public LOAI_SP LOAI_SP
		{
			get
			{
				return this._LOAI_SP.Entity;
			}
			set
			{
				LOAI_SP previousValue = this._LOAI_SP.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_SP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_SP.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._LOAI_SP.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._MA_LOAI = value.MA_LOAI;
					}
					else
					{
						this._MA_LOAI = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAI_SP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_SAN_PHAM", Storage="_MAU", ThisKey="MA_MAU", OtherKey="MA_MAU", IsForeignKey=true)]
		public MAU MAU
		{
			get
			{
				return this._MAU.Entity;
			}
			set
			{
				MAU previousValue = this._MAU.Entity;
				if (((previousValue != value) 
							|| (this._MAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAU.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._MAU.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._MA_MAU = value.MA_MAU;
					}
					else
					{
						this._MA_MAU = default(string);
					}
					this.SendPropertyChanged("MAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KICH_THUOCs(KICH_THUOC entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_KICH_THUOCs(KICH_THUOC entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
		
		private void attach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KH;
		
		private string _TEN_KH;
		
		private string _SDT;
		
		private string _DIA_CHI;
		
		private string _TEN_DN;
		
		private string _MK_DN;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAY_SINH;
		
		private string _HINH_ANH;
		
		private string _GIOI_TINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnTEN_KHChanging(string value);
    partial void OnTEN_KHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnTEN_DNChanging(string value);
    partial void OnTEN_DNChanged();
    partial void OnMK_DNChanging(string value);
    partial void OnMK_DNChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAY_SINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_SINHChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnGIOI_TINHChanging(string value);
    partial void OnGIOI_TINHChanged();
    #endregion
		
		public KHACH_HANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KH", DbType="NVarChar(30)")]
		public string TEN_KH
		{
			get
			{
				return this._TEN_KH;
			}
			set
			{
				if ((this._TEN_KH != value))
				{
					this.OnTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._TEN_KH = value;
					this.SendPropertyChanged("TEN_KH");
					this.OnTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(50)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DN", DbType="NVarChar(50)")]
		public string TEN_DN
		{
			get
			{
				return this._TEN_DN;
			}
			set
			{
				if ((this._TEN_DN != value))
				{
					this.OnTEN_DNChanging(value);
					this.SendPropertyChanging();
					this._TEN_DN = value;
					this.SendPropertyChanged("TEN_DN");
					this.OnTEN_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK_DN", DbType="NVarChar(50)")]
		public string MK_DN
		{
			get
			{
				return this._MK_DN;
			}
			set
			{
				if ((this._MK_DN != value))
				{
					this.OnMK_DNChanging(value);
					this.SendPropertyChanging();
					this._MK_DN = value;
					this.SendPropertyChanged("MK_DN");
					this.OnMK_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_SINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_SINH
		{
			get
			{
				return this._NGAY_SINH;
			}
			set
			{
				if ((this._NGAY_SINH != value))
				{
					this.OnNGAY_SINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_SINH = value;
					this.SendPropertyChanged("NGAY_SINH");
					this.OnNGAY_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NVarChar(200)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOI_TINH", DbType="NVarChar(4)")]
		public string GIOI_TINH
		{
			get
			{
				return this._GIOI_TINH;
			}
			set
			{
				if ((this._GIOI_TINH != value))
				{
					this.OnGIOI_TINHChanging(value);
					this.SendPropertyChanging();
					this._GIOI_TINH = value;
					this.SendPropertyChanged("GIOI_TINH");
					this.OnGIOI_TINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KICH_THUOC")]
	public partial class KICH_THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KICH_THUOC;
		
		private int _MA_SP;
		
		private string _TEN_KICH_THUOC;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KICH_THUOCChanging(int value);
    partial void OnMA_KICH_THUOCChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnTEN_KICH_THUOCChanging(string value);
    partial void OnTEN_KICH_THUOCChanged();
    #endregion
		
		public KICH_THUOC()
		{
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KICH_THUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KICH_THUOC
		{
			get
			{
				return this._MA_KICH_THUOC;
			}
			set
			{
				if ((this._MA_KICH_THUOC != value))
				{
					this.OnMA_KICH_THUOCChanging(value);
					this.SendPropertyChanging();
					this._MA_KICH_THUOC = value;
					this.SendPropertyChanged("MA_KICH_THUOC");
					this.OnMA_KICH_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KICH_THUOC", DbType="NVarChar(5)")]
		public string TEN_KICH_THUOC
		{
			get
			{
				return this._TEN_KICH_THUOC;
			}
			set
			{
				if ((this._TEN_KICH_THUOC != value))
				{
					this.OnTEN_KICH_THUOCChanging(value);
					this.SendPropertyChanging();
					this._TEN_KICH_THUOC = value;
					this.SendPropertyChanged("TEN_KICH_THUOC");
					this.OnTEN_KICH_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_KICH_THUOC", Storage="_SAN_PHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.KICH_THUOCs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.KICH_THUOCs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINH_ANH")]
	public partial class HINH_ANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HINH;
		
		private int _MA_SP;
		
		private string _HINH_ANH1;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HINHChanging(int value);
    partial void OnMA_HINHChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnHINH_ANH1Changing(string value);
    partial void OnHINH_ANH1Changed();
    #endregion
		
		public HINH_ANH()
		{
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_HINH
		{
			get
			{
				return this._MA_HINH;
			}
			set
			{
				if ((this._MA_HINH != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HINHChanging(value);
					this.SendPropertyChanging();
					this._MA_HINH = value;
					this.SendPropertyChanged("MA_HINH");
					this.OnMA_HINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HINH_ANH", Storage="_HINH_ANH1", DbType="NVarChar(200)")]
		public string HINH_ANH1
		{
			get
			{
				return this._HINH_ANH1;
			}
			set
			{
				if ((this._HINH_ANH1 != value))
				{
					this.OnHINH_ANH1Changing(value);
					this.SendPropertyChanging();
					this._HINH_ANH1 = value;
					this.SendPropertyChanged("HINH_ANH1");
					this.OnHINH_ANH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_HINH_ANH", Storage="_SAN_PHAM", ThisKey="MA_HINH", OtherKey="MA_SP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.HINH_ANHs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.HINH_ANHs.Add(this);
						this._MA_HINH = value.MA_SP;
					}
					else
					{
						this._MA_HINH = default(int);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
